### ISSUE TITLE
記事の版管理したい！！

### ISSUE THREAD

**Issue by yosei** [yosei/stack.lmlab.net#2]

**Comment by soheiyagi** [comment]
Paper tail
https://github.com/airblade/paper_trail

**Comment by yosei** [comment]
ありがとうございます！こんなピッタリなgemがあるんですね…！

**Comment by soheiyagi** [comment]
.versionsでVersion管理できるように。Viewでの見え方はまたご相談で
--
irb(main):001:0> stack = Stack.find 1
  Stack Load (12.4ms)  SELECT  `stacks`.* FROM `stacks` WHERE `stacks`.`id` = 1 LIMIT 1
=> #<Stack id: 1, title: "レギュレーション", problem: "マークダウンが使えると嬉しいかも？\r\n\r\nコードスニペット\r\n```\r\nalias rs=\"rail...", solution: "テーブル。\r\n<table>\r\n  <tr>\r\n    <th>A</th>\r\n    <th>B<...", explanation: "- 箇条書き1\r\n- 箇条書き2\r\n- 箇条書き3\r\n", url1: "", url2: "", url3: "", picture1: nil, picture2: nil, picture3: nil, user_id: 1, previous_id: nil, created_at: "2015-09-18 07:04:14", updated_at: "2015-10-15 07:16:27">
irb(main):002:0> stack.versions      
  PaperTrail::Version Load (5.1ms)  SELECT `versions`.* FROM `versions` WHERE `versions`.`item_id` = 1 AND `versions`.`item_type` = 'Stack'  ORDER BY `versions`.`created_at` ASC, `versions`.`id` ASC
=> #<ActiveRecord::Associations::CollectionProxy [#<PaperTrail::Version id: 1, item_type: "Stack", item_id: 1, event: "update", whodunnit: "2", object: "---\nid: 1\ntitle: \"レギュレーション\"\nproblem: |\n  マークダウンが使え...", created_at: "2015-10-15 04:59:05">, #<PaperTrail::Version id: 7, item_type: "Stack", item_id: 1, event: "update", whodunnit: "2", object: "---\nid: 1\ntitle: \"レギュレーション\"\nproblem: |\n  マークダウンが使え...", created_at: "2015-10-15 07:13:30">, #<PaperTrail::Version id: 8, item_type: "Stack", item_id: 1, event: "update", whodunnit: "2", object: "---\nid: 1\ntitle: \"レギュレーション\"\nproblem: \"マークダウンが使えると嬉...", created_at: "2015-10-15 07:16:27">]>
