### ISSUE TITLE
細々した課題

### ISSUE THREAD

**Issue by yosei** [yosei/stack.lmlab.net#5]
ログインフォーム、パスワードリマインダ、ユーザ登録フォームのデザイン。
ページネーションのローカライズ（日本語に）。編集フォームのローカライズ。

**Comment by yosei** [comment]
写真アップロード済みのテストケース。

**Comment by KaiShoya** [comment]
ローカライズ、写真アップロード済みのシードは終了しました。
デザインは現在取り組んでいます。
